# Generated by Django 4.2.4 on 2023-08-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
        ('accounts', '0003_alter_student_admin_alter_student_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='student_management_app.course'),
        ),
    ]
